const express = require('express')
const exphbs = require('express-handlebars')
const handlebars = require('handlebars')
const helpers = require('just-handlebars-helpers')
const bodyParser = require('body-parser')
const methodOverride = require('method-override')

const app = express()
app.engine('hbs', exphbs({ defaultLayout: 'main', extname: '.hbs'}))
app.set('view engine', 'hbs')
app.use(express.static('public'))
app.use(bodyParser.urlencoded({extended: true}))
app.use(methodOverride('_method'))

helpers.registerHelpers('handlebars')